[package]
name = "basesixtyfour"
version = "0.1.0"
authors = ["Thomas Irgang <thomas@irgang.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
